### ISSUE TITLE
Can't compile with Visual Studio 14.0 compiler

### ISSUE THREAD

**Issue by snummelin** [all3dp/meshprop#2]
Hi,

I am trying to use meshprop in node.js backend to get stl file properties. When doing npm install I get following error:

C:\work\3DF\node_modules\meshprop>if not defined npm_config_node_gyp (node "C:\Users\sami\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  meshprop.cpp
  plylib.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\hash_map(17): erro
r C2338: <hash_map> is deprecated and will be REMOVED. Please use <unordered_map>
. You can define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS to acknowledge that yo
u have received this warning. (compiling source file ..\lib\meshprop.cpp) [C:\wor
k\3DF\node_modules\meshprop\build\meshprop.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1

Any ideas?

Br,
Sami

**Comment by dreampulse** [comment]
Sorry, i've never tested under windows..

Pull requests are welcome! :-)
