### ISSUE TITLE
can't import mesh for OBJ, FBX, DAE data format

### ISSUE THREAD

**Issue by stvkim** [all3dp/meshprop#6]
Hi
Thank you for this great module. 
Sadly, I have been facing some problems with those mesh formats.
I have tested with STL, PLY, OBJ, DAE, totally 4 formats.
And I have figured that only STL and PLY are working with meshprop.

Here is the error message
> Error: can't import mesh

and here is the models that I've used
[models.zip](https://github.com/all3dp/meshprop/files/3733241/models.zip)

Please let me know if I am missing something

**Comment by henry-all3dp** [comment]
Hello @HeeJoong

Thanks for the issue and sorry for the late reply.

Yes, I can confirm that only STL and PLY are working consistently and reliable. The other file formats are taken from the website of the wrapped native [VCG library](http://vcg.isti.cnr.it/vcglib/fileformat.html). DAE is not supported by VCG.

We are sorry for the inconvenience this might have caused you. But `meshprop` relies on the importers provided by the VCG library.

I will update the docs to avoid confusion.
